const root=document.getElementById("adminApp");
let courses=TourStore.getCourses(),rides=TourStore.getRides(),selectedId=courses[0]?.id||null,selectedRideId=rides[0]?.id||null,adminSection="courses",modalState=null,dragImageIndex=null,dragVehicleImageIndex=null,dragGroupIndex=null,dragRouteState=null,expandedGroups=new Set();
const uid=p=>p+"-"+Date.now().toString(36);
const safe=(v="")=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const field=(id,label,value="",type="text",help="")=>`<div class="field"><label for="${id}">${label}</label><input id="${id}" type="${type}" value="${safe(value)}">${help?`<small class="help">${help}</small>`:""}</div>`;
const area=(id,label,value="")=>`<div class="field full"><label for="${id}">${label}</label><textarea id="${id}">${safe(value)}</textarea></div>`;
const current=()=>courses.find(c=>c.id===selectedId);
const persist=()=>TourStore.saveCourses(courses);
const num=id=>Number(document.getElementById(id)?.value||0),text=id=>document.getElementById(id)?.value.trim()||"",checked=id=>!!document.getElementById(id)?.checked;

function render(){if(adminSection==="vehicles")return renderVehicles();
 const c=current();
 root.innerHTML=`<div class="layout"><aside class="side"><div class="logo">TOURFORU <b>RIDE</b><small>ADMIN</small></div><nav><button class="on">관광상품 관리</button><button onclick="showVehicles()">차량 관리</button><button onclick="soon('가이드기사 관리')">가이드기사 관리</button><button onclick="soon('예약 관리')">예약 관리</button><button onclick="soon('결제 관리')">결제 관리</button><button onclick="soon('사이트 설정')">사이트 설정</button></nav><a class="site" href="../" target="_blank">홈페이지 보기 ↗</a></aside>
 <main class="main"><div class="head"><div><span class="eyebrow">CONTENT MANAGEMENT</span><h1>관광상품 관리</h1><p><strong>관광상품부터 세부코스까지</strong> 한 곳에서 등록하고 홈페이지 노출을 관리합니다.</p></div><button class="btn primary large" onclick="newCourse()">＋ 관광상품 추가</button></div>
 <div class="workspace"><section class="catalog panel"><div class="panel-head"><div><span class="section-label">PRODUCTS</span><h2>관광상품</h2></div><strong class="count">${courses.length}개</strong></div><div class="list">${courses.map((x,i)=>`<article class="item ${x.id===selectedId?"on":""}" onclick="pick('${x.id}')"><div class="item-copy"><strong>${safe(x.title)}</strong><span>${safe(x.location||"지역 미설정")} · 하위유형 ${x.groups?.length||0}개</span></div><div class="order"><button aria-label="위로" onclick="event.stopPropagation();moveCourse(${i},-1)">↑</button><button aria-label="아래로" onclick="event.stopPropagation();moveCourse(${i},1)">↓</button></div></article>`).join("")||"<div class='empty-admin'>등록된 상품이 없습니다.</div>"}</div></section>
 <section class="editor panel">${c?courseEditor(c):"<div class='empty-admin'>관광상품을 추가해주세요.</div>"}</section></div></main></div><div id="modalRoot"></div>`;
}
function showCourses(){adminSection="courses";render()}
function showVehicles(){adminSection="vehicles";render()}
function currentRide(){return rides.find(r=>r.id===selectedRideId)}
function persistRides(){TourStore.saveRides(rides)}
function renderVehicles(){const v=currentRide();root.innerHTML=`<div class="layout"><aside class="side"><div class="logo">TOURFORU <b>RIDE</b><small>ADMIN</small></div><nav><button onclick="showCourses()">관광상품 관리</button><button class="on">차량 관리</button><button onclick="soon('가이드기사 관리')">가이드기사 관리</button><button onclick="soon('예약 관리')">예약 관리</button><button onclick="soon('결제 관리')">결제 관리</button><button onclick="soon('사이트 설정')">사이트 설정</button></nav><a class="site" href="../" target="_blank">홈페이지 보기 ↗</a></aside><main class="main"><div class="head"><div><span class="eyebrow">FLEET MANAGEMENT</span><h1>차량 관리</h1><p><strong>자동매칭에 사용하는 차량 정보</strong>와 정비상태, 요금을 관리합니다.</p></div><button class="btn primary large" onclick="newRide()">＋ 차량 추가</button></div><div class="workspace"><section class="catalog panel"><div class="panel-head"><div><span class="section-label">VEHICLES</span><h2>차량</h2></div><strong class="count">${rides.length}대</strong></div><div class="list">${rides.map(x=>`<article class="item ${x.id===selectedRideId?"on":""}" onclick="pickRide('${x.id}')"><div class="item-copy"><strong>${safe(x.vehicle)}</strong><span>${safe(x.type||"-")} · ${x.capacity||0}인 · 짐 ${x.bags||0}개</span></div><span class="fleet-state ${x.active===false?"off":"on"}">${x.active===false?"중지":"운행"}</span></article>`).join("")||"<div class='empty-admin'>등록된 차량이 없습니다.</div>"}</div></section><section class="editor panel">${v?vehicleEditor(v):"<div class='empty-admin'>차량을 추가해주세요.</div>"}</section></div></main></div><div id="modalRoot"></div>`}
function driverOptions(v){const names=[...new Set((TOURFORU_DATA.rides||[]).map(r=>r.guide?.name).filter(Boolean))];const selected=v.driverName||v.guide?.name||"";return `<div class="driver-match"><div class="driver-search"><label for="vDriverSearch">기사 검색</label><input id="vDriverSearch" list="driverNames" value="${safe(selected)}" placeholder="기사 이름 검색 또는 선택"><datalist id="driverNames">${names.map(n=>`<option value="${safe(n)}">`).join("")}</datalist></div><button type="button" class="btn secondary" onclick="matchDriver()">기사 매칭</button>${selected?`<span class="matched-driver">현재 매칭 <b>${safe(selected)}</b></span>`:"<span class='matched-driver empty'>매칭 기사 없음</span>"}</div>`}
function vehicleEditor(v){return `<div class="editor-title"><div><span class="section-label">VEHICLE</span><h2>${safe(v.vehicle)}</h2><p>차량과 기사는 별도 관리하며 필요한 기사를 차량에 매칭합니다.</p></div><span class="status ${v.active===false?"off":"on"}">${v.active===false?"운행중지":"운행가능"}</span></div><div class="edit-block compact-block"><div class="block-head"><strong>기본 정보</strong><span>고객 화면과 자동매칭에 사용됩니다.</span></div><div class="fields vehicle-fields"><div class="field span-2"><label>차량명</label><input id="vName" value="${safe(v.vehicle)}"></div>${field("vType","차량 유형",v.type)}${field("vYear","연식",v.year)}${field("vNumber","차량번호",v.number||"")}${field("vCapacity","승차인원",v.capacity||0,"number")}${field("vBags","수하물(개)",v.bags||0,"number")}</div></div><div class="edit-block compact-block"><div class="block-head"><strong>기사 매칭</strong><span>차량과 기사는 서로 독립적으로 변경할 수 있습니다.</span></div>${driverOptions(v)}</div><div class="edit-block compact-block split-block"><div><div class="block-head"><strong>요금</strong><span>예상금액 계산</span></div><div class="fields rate-fields">${field("vBase","기본요금(원)",v.basePrice||0,"number")}${field("vHourly","시간당 추가요금(원)",v.hourly||0,"number")}</div></div><div><div class="block-head"><strong>정비 · 안전</strong><span>고객 제공 차량 이력</span></div><div class="fields maintenance-fields">${field("vMaintLast","최근 정비일",v.maintenance?.last||"")}${field("vMileage","주행거리",v.maintenance?.mileage||"")}${field("vMaintNext","다음 점검",v.maintenance?.next||"")}${field("vInspection","점검 상태",v.maintenance?.inspection||"정상")}</div></div></div><div class="edit-block compact-block"><div class="block-head"><strong>차량 사진</strong><span><b>최대 10장</b> · 대표사진 체크 · 드래그 순서 변경</span></div><label class="upload-box" for="vehicleImages"><span class="upload-icon">＋</span><strong>차량 사진 추가</strong><small>복수 선택 가능</small><input id="vehicleImages" type="file" accept="image/*" multiple onchange="handleVehicleImages(this.files)"></label><div class="image-grid vehicle-image-grid">${vehicleImages(v).map((src,i)=>vehicleImageTile(src,i,v)).join("")||"<div class='image-empty'>등록된 차량 사진이 없습니다.</div>"}</div></div><div class="vehicle-bottom"><label class="toggle-card"><input id="vActive" type="checkbox" ${v.active===false?"":"checked"}><span><strong>운행 가능</strong><small>자동매칭 후보에 포함</small></span></label><div class="editor-actions"><button class="btn primary" onclick="saveRide()">변경사항 저장</button><button class="btn danger ghost" onclick="removeRide()">차량 삭제</button></div></div>`}
function matchDriver(){const v=currentRide(),name=text("vDriverSearch");v.driverName=name;persistRides();renderVehicles();toast(name?name+" 기사와 매칭했습니다.":"기사 매칭을 해제했습니다.")}
function pickRide(id){selectedRideId=id;renderVehicles()}
function newRide(){const v={id:uid("vehicle"),vehicle:"새 차량",type:"",year:"",number:"",capacity:4,bags:2,image:"",maintenance:{last:"",mileage:"",next:"",inspection:"정상"},basePrice:0,hourly:0,active:false};rides.push(v);selectedRideId=v.id;persistRides();renderVehicles()}
function saveRide(){const v=currentRide();Object.assign(v,{vehicle:text("vName"),type:text("vType"),year:text("vYear"),number:text("vNumber"),capacity:num("vCapacity"),bags:num("vBags"),basePrice:num("vBase"),hourly:num("vHourly"),active:checked("vActive"),driverName:text("vDriverSearch")||v.driverName||"",maintenance:{last:text("vMaintLast"),mileage:text("vMileage"),next:text("vMaintNext"),inspection:text("vInspection")}});persistRides();renderVehicles();toast("차량 정보를 저장했습니다.")}
function vehicleImages(v){return v.images?.length?v.images:(v.image?[v.image]:[])}
function vehicleImageTile(src,i,v){const hero=(v.image||"")===src;return `<div class="image-tile ${hero?"is-hero":""}" draggable="true" ondragstart="vehicleImageDragStart(${i})" ondragover="vehicleImageDragOver(event)" ondrop="vehicleImageDrop(event,${i})" ondragend="vehicleImageDragEnd()"><div class="drag-hint">⋮⋮ 순서 변경</div><img src="${safe(src)}" alt="차량 이미지 ${i+1}"><div class="image-meta"><label class="hero-check"><input type="radio" name="vehicleHero" ${hero?"checked":""} onchange="setVehicleHero(${i})"><span>대표 사진</span></label><div><span class="image-number">#${i+1}</span><button class="mini danger-text" onclick="removeVehicleImage(${i})">삭제</button></div></div></div>`}
async function handleVehicleImages(files){if(!files?.length)return;const v=currentRide();v.images=vehicleImages(v);const room=10-v.images.length;if(room<=0)return alert("차량 사진은 최대 10장까지 등록할 수 있습니다.");const chosen=[...files].slice(0,room);for(const file of chosen){if(!file.type.startsWith("image/"))continue;if(file.size>2*1024*1024){alert(file.name+"은 2MB를 초과해 등록하지 않았습니다.");continue}v.images.push(await fileToDataUrl(file))}if(!v.image)v.image=v.images[0]||"";persistRides();renderVehicles();if(files.length>room)alert("차량 사진은 최대 10장까지 등록됩니다.");toast("차량 사진을 추가했습니다.")}
function setVehicleHero(i){const v=currentRide();v.images=vehicleImages(v);v.image=v.images[i]||"";persistRides();renderVehicles();toast("대표 차량 사진을 변경했습니다.")}
function vehicleImageDragStart(i){dragVehicleImageIndex=i;requestAnimationFrame(()=>document.querySelectorAll(".vehicle-image-grid .image-tile")[i]?.classList.add("dragging"))}
function vehicleImageDragOver(e){e.preventDefault();e.currentTarget.classList.add("drag-over")}
function vehicleImageDrop(e,target){e.preventDefault();document.querySelectorAll(".vehicle-image-grid .image-tile").forEach(el=>el.classList.remove("drag-over"));if(dragVehicleImageIndex===null||dragVehicleImageIndex===target)return;const v=currentRide();v.images=vehicleImages(v);const [moved]=v.images.splice(dragVehicleImageIndex,1);v.images.splice(target,0,moved);persistRides();dragVehicleImageIndex=null;renderVehicles();toast("차량 사진 순서를 변경했습니다.")}
function vehicleImageDragEnd(){dragVehicleImageIndex=null;document.querySelectorAll(".vehicle-image-grid .image-tile").forEach(el=>el.classList.remove("dragging","drag-over"))}
function removeVehicleImage(i){const v=currentRide();v.images=vehicleImages(v);const removed=v.images[i];v.images.splice(i,1);if(v.image===removed)v.image=v.images[0]||"";persistRides();renderVehicles()}
function removeRide(){if(!confirm("이 차량을 삭제할까요?"))return;rides=rides.filter(r=>r.id!==selectedRideId);selectedRideId=rides[0]?.id||null;persistRides();renderVehicles()}
function courseEditor(c){const imgs=c.images?.length?c.images:(c.hero?[c.hero]:[]);return `
 <div class="editor-title"><div><span class="section-label">TOUR PRODUCT</span><h2>${safe(c.title)}</h2><p>기본 정보, 이미지, 노출 설정을 편집합니다.</p></div><span class="status ${c.published===false?"off":"on"}">${c.published===false?"비공개":"공개"}</span></div>
 <div class="edit-block"><div class="block-head"><strong>기본 정보</strong><span>홈페이지 상품 카드와 상세화면에 사용됩니다.</span></div><div class="fields">${field("title","상품명",c.title)}${field("location","지역",c.location)}${field("category","카테고리",c.category)}${field("views","조회수",c.views||0,"number")}${area("description","상품 설명",c.description)}</div></div>
 <div class="edit-block"><div class="block-head"><strong>상품 이미지</strong><span><b>대표 이미지를 직접 체크</b>하고, 이미지는 마우스로 끌어서 순서를 변경할 수 있습니다.</span></div>
 <label class="upload-box" for="imageFiles"><span class="upload-icon">＋</span><strong>이미지 추가</strong><small>JPG, PNG, WEBP · 복수 선택 가능</small><input id="imageFiles" type="file" accept="image/*" multiple onchange="handleImages(this.files)"></label>
 <div class="image-grid">${imgs.map((src,i)=>imageTile(src,i)).join("")||"<div class='image-empty'>등록된 이미지가 없습니다.</div>"}</div></div>
 <div class="edit-block"><div class="block-head"><strong>노출 설정</strong><span>추천 여부와 홈페이지 공개 상태를 정합니다.</span></div><div class="settings-row"><label class="toggle-card"><input id="featured" type="checkbox" ${c.featured?"checked":""}><span><strong>추천상품</strong><small>홈페이지 추천 영역에 노출</small></span></label><label class="toggle-card"><input id="published" type="checkbox" ${c.published===false?"":"checked"}><span><strong>홈페이지 공개</strong><small>고객이 상품을 볼 수 있음</small></span></label><div class="compact-field"><label for="sortOrder">노출순서</label><input id="sortOrder" type="number" value="${c.sortOrder||0}"></div></div></div>
 <div class="editor-actions"><button class="btn primary" onclick="saveCourse()">변경사항 저장</button><button class="btn" onclick="previewCourse()">홈페이지에서 보기</button><button class="btn danger ghost" onclick="removeCourse()">상품 삭제</button></div>
 <div class="child-section"><div class="section-head"><div><span class="section-label">CHILD COURSES</span><h2>하위 여행유형</h2><p><strong>이순신 승전길</strong>처럼 여러 여행방식과 세부코스를 가진 상품을 구성합니다.</p></div><button class="btn secondary" onclick="openGroupForm()">＋ 여행유형 추가</button></div>
 ${(c.groups||[]).map((g,i)=>groupCard(g,i)).join("")||"<div class='empty-admin small'>하위 여행유형이 없습니다.</div>"}</div>`}
function imageTile(src,i){const c=current(),isHero=(c.hero||"")===src;return `<div class="image-tile ${isHero?"is-hero":""}" draggable="true" ondragstart="imageDragStart(${i})" ondragover="imageDragOver(event)" ondrop="imageDrop(event,${i})" ondragend="imageDragEnd()"><div class="drag-hint">⋮⋮ 드래그하여 순서 변경</div><img src="${safe(src)}" alt="상품 이미지 ${i+1}"><div class="image-meta"><label class="hero-check"><input type="radio" name="heroImage" ${isHero?"checked":""} onchange="setHeroImage(${i})"><span>대표 이미지</span></label><div><span class="image-number">#${i+1}</span><button class="mini danger-text" onclick="removeImage(${i})">삭제</button></div></div></div>`}
function groupCard(g,i){const open=expandedGroups.has(g.id);return `<div class="group ${open?"expanded":""}" draggable="true" ondragstart="groupDragStart(event,${i})" ondragover="sortDragOver(event)" ondrop="groupDrop(event,${i})" ondragend="sortDragEnd()"><div class="group-title" onclick="toggleGroup('${g.id}')"><div class="group-main"><span class="drag-grip" title="드래그하여 순서 변경">⋮⋮</span><span class="group-label">유형 ${i+1}</span><strong>${safe(g.title)}</strong><span class="group-summary">${safe(g.description||"설명 없음")}</span><span class="child-count">세부코스 ${g.routes?.length||0}</span></div><div class="row" onclick="event.stopPropagation()"><button class="btn" onclick="openGroupForm('${g.id}')">수정</button><button class="btn secondary" onclick="openRouteForm('${g.id}')">＋ 세부코스</button><button class="btn danger ghost" onclick="removeGroup('${g.id}')">삭제</button></div></div>${open?`<div class="route-list-admin">${(g.routes||[]).map((r,ri)=>routeRow(g,r,ri)).join("")||"<div class='empty-admin small'>세부코스가 없습니다.</div>"}</div>`:""}</div>`}
function routeRow(g,r,i){const pointCount=(r.points||[]).length||(r.stops||[]).length;return `<div class="route" draggable="true" ondragstart="routeDragStart(event,'${g.id}',${i})" ondragover="sortDragOver(event)" ondrop="routeDrop(event,'${g.id}',${i})" ondragend="sortDragEnd()"><div class="route-main"><span class="drag-grip" title="드래그하여 순서 변경">⋮⋮</span><strong>${safe(r.title)}</strong><span>${safe(r.area||"-")} · ${r.distance||0}km · 약 ${r.walkHours||0}시간 · 코스지점 ${pointCount}개 · 이미지 ${(r.images||[]).length}장</span></div><div class="row"><button class="btn" onclick="openRouteForm('${g.id}','${r.id}')">수정</button><button class="btn danger ghost" onclick="removeRoute('${g.id}','${r.id}')">삭제</button></div></div>`}
function toggleGroup(id){expandedGroups.has(id)?expandedGroups.delete(id):expandedGroups.add(id);render()}
function sortDragOver(e){e.preventDefault();e.currentTarget.classList.add("sort-over")}
function sortDragEnd(){document.querySelectorAll(".group,.route").forEach(el=>el.classList.remove("sort-over","sort-dragging"));dragGroupIndex=null;dragRouteState=null}
function groupDragStart(e,i){if(e.target.closest("button")){e.preventDefault();return}dragGroupIndex=i;e.currentTarget.classList.add("sort-dragging");e.dataTransfer.effectAllowed="move"}
function groupDrop(e,target){e.preventDefault();e.stopPropagation();if(dragGroupIndex===null||dragGroupIndex===target)return sortDragEnd();const arr=current().groups,[moved]=arr.splice(dragGroupIndex,1);arr.splice(target,0,moved);persist();sortDragEnd();render();toast("여행유형 순서를 변경했습니다.")}
function routeDragStart(e,gid,i){if(e.target.closest("button")){e.preventDefault();return}e.stopPropagation();dragRouteState={gid,i};e.currentTarget.classList.add("sort-dragging");e.dataTransfer.effectAllowed="move"}
function routeDrop(e,gid,target){e.preventDefault();e.stopPropagation();if(!dragRouteState||dragRouteState.gid!==gid||dragRouteState.i===target)return sortDragEnd();const arr=current().groups.find(g=>g.id===gid).routes,[moved]=arr.splice(dragRouteState.i,1);arr.splice(target,0,moved);persist();sortDragEnd();render();toast("세부코스 순서를 변경했습니다.")}
async function handleImages(files){if(!files?.length)return;const c=current();c.images=c.images?.length?c.images:(c.hero?[c.hero]:[]);for(const file of [...files]){if(!file.type.startsWith("image/"))continue;if(file.size>2*1024*1024){alert(file.name+"은 2MB를 초과해 현재 프로토타입 저장소에 넣을 수 없습니다.");continue}c.images.push(await fileToDataUrl(file))}if(!c.hero)c.hero=c.images[0]||"";persist();render();toast(files.length+"개 이미지 선택을 처리했습니다.")}
function fileToDataUrl(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)})}
function setHeroImage(i){const c=current();c.images=c.images?.length?c.images:(c.hero?[c.hero]:[]);c.hero=c.images[i]||"";persist();render();toast("대표 이미지를 변경했습니다.")}
function imageDragStart(i){dragImageIndex=i;requestAnimationFrame(()=>document.querySelectorAll(".image-tile")[i]?.classList.add("dragging"))}
function imageDragOver(e){e.preventDefault();e.currentTarget.classList.add("drag-over")}
function imageDrop(e,target){e.preventDefault();document.querySelectorAll(".image-tile").forEach(el=>el.classList.remove("drag-over"));if(dragImageIndex===null||dragImageIndex===target)return;const c=current();c.images=c.images?.length?c.images:(c.hero?[c.hero]:[]);const [moved]=c.images.splice(dragImageIndex,1);c.images.splice(target,0,moved);persist();dragImageIndex=null;render();toast("이미지 순서를 변경했습니다.")}
function imageDragEnd(){dragImageIndex=null;document.querySelectorAll(".image-tile").forEach(el=>el.classList.remove("dragging","drag-over"))}
function removeImage(i){const c=current();c.images=c.images?.length?c.images:(c.hero?[c.hero]:[]);const removed=c.images[i];c.images.splice(i,1);if(c.hero===removed)c.hero=c.images[0]||"";persist();render()}
function modal(title,body,saveAction){document.getElementById("modalRoot").innerHTML=`<div class="modal-backdrop" onclick="if(event.target===this)closeModal()"><div class="modal"><div class="modal-head"><div><span class="section-label">EDITOR</span><h2>${title}</h2></div><button class="close" onclick="closeModal()">×</button></div><div class="modal-body">${body}</div><div class="modal-actions"><button class="btn" onclick="closeModal()">취소</button><button class="btn primary" onclick="${saveAction}">저장</button></div></div></div>`}
function closeModal(){document.getElementById("modalRoot").innerHTML="";modalState=null}
function newCourse(){const c={id:uid("course"),title:"새 관광상품",location:"",category:"",description:"",hero:"",images:[],featured:false,published:false,views:0,sortOrder:courses.length+1,groups:[]};courses.push(c);selectedId=c.id;persist();render()}
function pick(id){selectedId=id;render()}
function saveCourse(){const c=current();Object.assign(c,{title:text("title"),location:text("location"),category:text("category"),description:text("description"),views:num("views"),sortOrder:num("sortOrder"),featured:checked("featured"),published:checked("published")});if(!c.hero&&c.images?.length)c.hero=c.images[0];persist();render();toast("관광상품을 저장했습니다.")}
function removeCourse(){if(!confirm("이 상품과 모든 하위코스를 삭제할까요?"))return;courses=courses.filter(c=>c.id!==selectedId);selectedId=courses[0]?.id||null;persist();render()}
function previewCourse(){window.open("../","_blank")}
function openGroupForm(id=null){const c=current(),g=id?c.groups.find(x=>x.id===id):{title:"",description:"",published:true};modalState={type:"group",id};modal(id?"여행유형 수정":"여행유형 추가",`${field("mGroupTitle","여행유형명",g.title)}${area("mGroupDescription","설명",g.description)}<div class="field full checks"><label><input id="mGroupPublished" type="checkbox" ${g.published===false?"":"checked"}> <strong>홈페이지 공개</strong></label></div>`,"saveGroup()")}
function saveGroup(){const c=current();let g=modalState.id?c.groups.find(x=>x.id===modalState.id):null;if(!text("mGroupTitle"))return alert("여행유형명을 입력해주세요.");if(!g){g={id:uid("group"),routes:[]};(c.groups??=[]).push(g)}Object.assign(g,{title:text("mGroupTitle"),description:text("mGroupDescription"),published:checked("mGroupPublished")});persist();closeModal();render()}
function removeGroup(id){if(!confirm("여행유형과 그 안의 세부코스를 삭제할까요?"))return;current().groups=current().groups.filter(g=>g.id!==id);persist();render()}
function routePointRows(points=[]){return points.map((p,i)=>`<div class="point-row" data-point-row data-lat="${safe(p.lat||"")}" data-lng="${safe(p.lng||"")}"><span class="point-order">${i+1}</span><select class="point-type"><option ${p.type==="출발지"?"selected":""}>출발지</option><option ${p.type==="경유지"?"selected":""}>경유지</option><option ${p.type==="도착지"?"selected":""}>도착지</option></select><div class="place-search"><input class="point-name" placeholder="장소명 또는 주소 검색" value="${safe(p.name||"")}" onkeydown="if(event.key==='Enter'){event.preventDefault();searchPoint(this)}"><button type="button" class="mini" onclick="searchPoint(this.previousElementSibling)">검색</button><div class="place-results"></div></div><input class="point-address" placeholder="선택한 주소" value="${safe(p.address||"")}" readonly><button type="button" class="mini danger-text" onclick="this.closest('[data-point-row]').remove();renumberPoints();refreshRouteMap()">삭제</button></div>`).join("")}
function routeImageRows(images=[]){return images.map((src,i)=>`<div class="route-image-tile" draggable="true" ondragstart="routeImageDragStart(event,${i})" ondragover="routeImageDragOver(event)" ondrop="routeImageDrop(event,${i})" ondragend="routeImageDragEnd()"><span class="route-image-grip">⋮⋮</span><img src="${safe(src)}" alt="세부코스 이미지 ${i+1}"><div><strong>이미지 ${i+1}</strong><button type="button" class="mini danger-text" onclick="removePendingRouteImage(${i})">삭제</button></div></div>`).join("")}
function openRouteForm(gid,rid=null){const g=current().groups.find(x=>x.id===gid),r=rid?g.routes.find(x=>x.id===rid):{title:"",area:"",distance:0,walkHours:0,transportHours:0,difficulty:"보통",description:"",stops:[],points:[],images:[],published:true};const legacy=(r.stops||[]).map((name,i,a)=>({type:i===0?"출발지":i===a.length-1?"도착지":"경유지",name,address:""}));modalState={type:"route",gid,rid,routeImages:[...(r.images||[])],points:[...(r.points?.length?r.points:legacy)],routePath:[...(r.path||[])],drawRoute:false};modal(rid?"세부코스 수정":"세부코스 추가",`<div class="fields">${field("mRouteTitle","세부코스명",r.title)}${field("mRouteArea","지역",r.area)}${field("mRouteDistance","거리(km)",r.distance,"number")}${field("mRouteWalk","트래킹 시간",r.walkHours,"number")}${field("mRouteTransport","차량 이동시간",r.transportHours,"number")}${field("mRouteDifficulty","난이도",r.difficulty)}${area("mRouteDescription","코스 설명",r.description)}</div><div class="modal-section"><div class="modal-section-head"><div><strong>코스 지점</strong><small>출발지 → 경유지 → 도착지 순서로 등록합니다.</small></div><button type="button" class="btn secondary" onclick="addPointRow()">＋ 지점 추가</button></div><div class="route-mode"><strong>경로 방식</strong><label><input type="radio" name="routeMode" value="WALK" ${(r.routeMode||"WALK")==="WALK"?"checked":""} onchange="refreshRouteMap()"> 도보</label><label><input type="radio" name="routeMode" value="CAR" ${r.routeMode==="CAR"?"checked":""} onchange="refreshRouteMap()"> 차량</label><label><input type="radio" name="routeMode" value="BICYCLE" ${r.routeMode==="BICYCLE"?"checked":""} onchange="refreshRouteMap()"> 자전거</label></div><div id="pointRows" class="point-rows">${routePointRows(modalState.points)}</div><div class="route-path-tools"><button type="button" class="btn primary" id="autoCarRouteBtn" onclick="generateCarRoute()">🚗 차량 실제경로 자동생성</button><button type="button" class="btn secondary" id="drawRouteBtn" onclick="toggleRouteDrawing()">✎ 경로 직접 그리기</button><button type="button" class="btn" onclick="clearRoutePath()">경로선 지우기</button><small id="routePathStatus">${(r.path||[]).length?"저장된 상세 경로 "+r.path.length+"개 좌표":"상세 경로가 없습니다. 지점 직선은 저장되지 않습니다."}</small></div><div id="routeMap" class="route-map"></div></div><div class="modal-section"><div class="modal-section-head"><div><strong>세부코스 사진</strong><small><b>여러 장을 한 번에 선택</b>할 수 있고, 등록 후 드래그하여 순서를 변경합니다.</small></div></div><label class="route-upload-box" for="routeImageFiles"><span>＋</span><strong>사진 첨부</strong><small>JPG, PNG, WEBP · 복수 선택 가능</small><input id="routeImageFiles" type="file" accept="image/*" multiple onchange="handleRouteImages(this.files)"></label><div id="routeImageGrid" class="route-image-grid">${routeImageRows(modalState.routeImages)}</div></div><div class="field full checks"><label><input id="mRoutePublished" type="checkbox" ${r.published===false?"":"checked"}> <strong>홈페이지 공개</strong></label></div>`,"saveRoute()");setTimeout(refreshRouteMap,0)}
function addPointRow(){const box=document.getElementById("pointRows");box.insertAdjacentHTML("beforeend",routePointRows([{type:box.children.length?"경유지":"출발지",name:"",address:""}]));renumberPoints();refreshRouteMap()}
function renumberPoints(){document.querySelectorAll("[data-point-row] .point-order").forEach((el,i)=>el.textContent=i+1)}
function collectPoints(){return [...document.querySelectorAll("[data-point-row]")].map(row=>({type:row.querySelector(".point-type").value,name:row.querySelector(".point-name").value.trim(),address:row.querySelector(".point-address").value.trim(),lat:Number(row.dataset.lat)||null,lng:Number(row.dataset.lng)||null})).filter(p=>p.name)}
function searchPoint(input){const q=input.value.trim(),row=input.closest("[data-point-row]"),box=row.querySelector(".place-results");if(!q)return;if(!window.kakao?.maps?.services)return alert("카카오맵을 불러오지 못했습니다. 카카오 Developers의 JavaScript SDK 도메인을 확인해주세요.");const show=data=>box.innerHTML=data.slice(0,5).map(p=>`<button type="button" class="place-result" onclick="selectPointResult(this)" data-name="${safe(p.place_name||q)}" data-address="${safe(p.road_address_name||p.address_name)}" data-lat="${p.y}" data-lng="${p.x}"><b>${safe(p.place_name||q)}</b><small>${safe(p.road_address_name||p.address_name)}</small></button>`).join("");new kakao.maps.services.Places().keywordSearch(q,(data,status)=>{if(status===kakao.maps.services.Status.OK)return show(data);new kakao.maps.services.Geocoder().addressSearch(q,(addr,addrStatus)=>{if(addrStatus===kakao.maps.services.Status.OK)return show(addr.map(x=>({...x,place_name:q,y:x.y,x:x.x})));box.innerHTML="<button type=\"button\" class=\"place-result\">검색 결과가 없습니다.</button>"})})}
function selectPointResult(btn){const row=btn.closest("[data-point-row]");row.querySelector(".point-name").value=btn.dataset.name;row.querySelector(".point-address").value=btn.dataset.address;row.dataset.lat=btn.dataset.lat;row.dataset.lng=btn.dataset.lng;row.querySelector(".place-results").innerHTML="";refreshRouteMap()}
function refreshRouteMap(){const el=document.getElementById("routeMap");if(!el||!window.kakao?.maps)return;const pts=collectPoints().filter(p=>p.lat&&p.lng),saved=modalState?.routePath||[],base=saved.length?saved:pts;const center=base[0]?new kakao.maps.LatLng(base[0].lat,base[0].lng):new kakao.maps.LatLng(35.1796,128.1076),map=new kakao.maps.Map(el,{center,level:8}),bounds=new kakao.maps.LatLngBounds();pts.forEach((p,i)=>{const pos=new kakao.maps.LatLng(p.lat,p.lng);bounds.extend(pos);new kakao.maps.Marker({map,position:pos,title:(i+1)+" "+p.name})});if(saved.length>1){const path=saved.map(p=>{const pos=new kakao.maps.LatLng(p.lat,p.lng);bounds.extend(pos);return pos});new kakao.maps.Polyline({map,path,strokeWeight:6,strokeOpacity:.85,strokeStyle:"solid"})}else if(pts.length>1){const preview=pts.map(p=>new kakao.maps.LatLng(p.lat,p.lng));new kakao.maps.Polyline({map,path:preview,strokeWeight:3,strokeOpacity:.35,strokeStyle:"shortdash"})}if(base.length)map.setBounds(bounds);if(modalState?.drawRoute)kakao.maps.event.addListener(map,"click",e=>{modalState.routePath.push({lat:e.latLng.getLat(),lng:e.latLng.getLng()});updateRoutePathStatus();refreshRouteMap()})}
async function generateCarRoute(){const pts=collectPoints().filter(p=>p.lat&&p.lng);if(pts.length<2)return alert("출발지와 도착지를 지도 검색으로 먼저 지정해주세요.");const btn=document.getElementById("autoCarRouteBtn"),url=window.TOURFORU_API_BASE;if(!url)return alert("자동 차량경로 API 서버 주소가 아직 설정되지 않았습니다. 서버 배포 후 바로 연결됩니다.");try{btn.disabled=true;btn.textContent="경로 계산 중…";const res=await fetch(url.replace(/\/$/,"")+"/api/routes/car",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({points:pts})});const data=await res.json();if(!res.ok)throw new Error(data.error||"경로 생성 실패");modalState.routePath=data.path||[];modalState.drawRoute=false;const mode=document.querySelector('input[name="routeMode"][value="CAR"]');if(mode)mode.checked=true;updateRoutePathStatus();refreshRouteMap();toast("실제 차량 도로경로를 생성했습니다.")}catch(e){alert("차량 경로 생성 실패: "+e.message)}finally{btn.disabled=false;btn.textContent="🚗 차량 실제경로 자동생성"}}
function toggleRouteDrawing(){if(!modalState)return;modalState.drawRoute=!modalState.drawRoute;const b=document.getElementById("drawRouteBtn");if(b)b.textContent=modalState.drawRoute?"✓ 경로 그리기 종료":"✎ 경로 직접 그리기";updateRoutePathStatus();refreshRouteMap()}
function clearRoutePath(){if(!modalState)return;modalState.routePath=[];modalState.drawRoute=false;updateRoutePathStatus();refreshRouteMap()}
function updateRoutePathStatus(){const el=document.getElementById("routePathStatus"),b=document.getElementById("drawRouteBtn");if(el)el.textContent=modalState.drawRoute?"지도에서 실제 이동선을 따라 차례로 클릭하세요. 현재 "+modalState.routePath.length+"개 좌표":modalState.routePath.length?"상세 경로 "+modalState.routePath.length+"개 좌표":"상세 경로가 없습니다. 점선은 지점 연결 미리보기입니다.";if(b)b.textContent=modalState.drawRoute?"✓ 경로 그리기 종료":"✎ 경로 직접 그리기"}

async function handleRouteImages(files){for(const file of [...files]){if(!file.type.startsWith("image/"))continue;if(file.size>2*1024*1024){alert(file.name+"은 2MB를 초과해 현재 프로토타입 저장소에 넣을 수 없습니다.");continue}modalState.routeImages.push(await fileToDataUrl(file))}document.getElementById("routeImageGrid").innerHTML=routeImageRows(modalState.routeImages)}
function removePendingRouteImage(i){modalState.routeImages.splice(i,1);document.getElementById("routeImageGrid").innerHTML=routeImageRows(modalState.routeImages)}
function routeImageDragStart(e,i){modalState.dragRouteImage=i;e.currentTarget.classList.add("dragging");e.dataTransfer.effectAllowed="move"}
function routeImageDragOver(e){e.preventDefault();e.currentTarget.classList.add("drag-over")}
function routeImageDrop(e,target){e.preventDefault();const from=modalState.dragRouteImage;if(from===undefined||from===target)return routeImageDragEnd();const [moved]=modalState.routeImages.splice(from,1);modalState.routeImages.splice(target,0,moved);modalState.dragRouteImage=undefined;document.getElementById("routeImageGrid").innerHTML=routeImageRows(modalState.routeImages)}
function routeImageDragEnd(){modalState.dragRouteImage=undefined;document.querySelectorAll(".route-image-tile").forEach(el=>el.classList.remove("dragging","drag-over"))}
function saveRoute(){const {gid,rid}=modalState,g=current().groups.find(x=>x.id===gid);if(!text("mRouteTitle"))return alert("세부코스명을 입력해주세요.");let r=rid?g.routes.find(x=>x.id===rid):null;if(!r){r={id:uid("route"),views:0};(g.routes??=[]).push(r)}const points=collectPoints();Object.assign(r,{title:text("mRouteTitle"),area:text("mRouteArea"),distance:num("mRouteDistance"),walkHours:num("mRouteWalk"),transportHours:num("mRouteTransport"),difficulty:text("mRouteDifficulty")||"보통",description:text("mRouteDescription"),points,stops:points.map(p=>p.name),images:[...modalState.routeImages],routeMode:document.querySelector('input[name="routeMode"]:checked')?.value||"WALK",path:[...(modalState.routePath||[])],pathSource:(modalState.routePath||[]).length?"manual":null,published:checked("mRoutePublished")});persist();closeModal();render();toast("세부코스를 저장했습니다.")}
function removeRoute(gid,rid){if(!confirm("세부코스를 삭제할까요?"))return;const g=current().groups.find(x=>x.id===gid);g.routes=g.routes.filter(r=>r.id!==rid);persist();render()}
function move(arr,i,d,rerender=true){const n=i+d;if(n<0||n>=arr.length)return;[arr[i],arr[n]]=[arr[n],arr[i]];persist();if(rerender)render()}
function moveCourse(i,d){move(courses,i,d)}function moveGroup(i,d){move(current().groups,i,d)}function moveRoute(gid,i,d){move(current().groups.find(g=>g.id===gid).routes,i,d)}
function toast(msg){const el=document.createElement("div");el.className="admin-toast";el.textContent=msg;document.body.appendChild(el);setTimeout(()=>el.remove(),1800)}
function soon(name){alert(name+"는 다음 관리모듈에서 연결합니다.")}
render();