const root=document.getElementById("adminApp");
let courses=TourStore.getCourses(),selectedId=courses[0]?.id||null,modalState=null,dragImageIndex=null;
const uid=p=>p+"-"+Date.now().toString(36);
const safe=(v="")=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const field=(id,label,value="",type="text",help="")=>`<div class="field"><label for="${id}">${label}</label><input id="${id}" type="${type}" value="${safe(value)}">${help?`<small class="help">${help}</small>`:""}</div>`;
const area=(id,label,value="")=>`<div class="field full"><label for="${id}">${label}</label><textarea id="${id}">${safe(value)}</textarea></div>`;
const current=()=>courses.find(c=>c.id===selectedId);
const persist=()=>TourStore.saveCourses(courses);
const num=id=>Number(document.getElementById(id)?.value||0),text=id=>document.getElementById(id)?.value.trim()||"",checked=id=>!!document.getElementById(id)?.checked;

function render(){
 const c=current();
 root.innerHTML=`<div class="layout"><aside class="side"><div class="logo">TOURFORU <b>RIDE</b><small>ADMIN</small></div><nav><button class="on">관광상품 관리</button><button onclick="soon('차량 관리')">차량 관리</button><button onclick="soon('가이드기사 관리')">가이드기사 관리</button><button onclick="soon('예약 관리')">예약 관리</button><button onclick="soon('결제 관리')">결제 관리</button><button onclick="soon('사이트 설정')">사이트 설정</button></nav><a class="site" href="../" target="_blank">홈페이지 보기 ↗</a></aside>
 <main class="main"><div class="head"><div><span class="eyebrow">CONTENT MANAGEMENT</span><h1>관광상품 관리</h1><p><strong>관광상품부터 세부코스까지</strong> 한 곳에서 등록하고 홈페이지 노출을 관리합니다.</p></div><button class="btn primary large" onclick="newCourse()">＋ 관광상품 추가</button></div>
 <div class="workspace"><section class="catalog panel"><div class="panel-head"><div><span class="section-label">PRODUCTS</span><h2>관광상품</h2></div><strong class="count">${courses.length}개</strong></div><div class="list">${courses.map((x,i)=>`<article class="item ${x.id===selectedId?"on":""}" onclick="pick('${x.id}')"><div class="item-copy"><strong>${safe(x.title)}</strong><span>${safe(x.location||"지역 미설정")} · 하위유형 ${x.groups?.length||0}개</span></div><div class="order"><button aria-label="위로" onclick="event.stopPropagation();moveCourse(${i},-1)">↑</button><button aria-label="아래로" onclick="event.stopPropagation();moveCourse(${i},1)">↓</button></div></article>`).join("")||"<div class='empty-admin'>등록된 상품이 없습니다.</div>"}</div></section>
 <section class="editor panel">${c?courseEditor(c):"<div class='empty-admin'>관광상품을 추가해주세요.</div>"}</section></div></main></div><div id="modalRoot"></div>`;
}
function courseEditor(c){const imgs=c.images?.length?c.images:(c.hero?[c.hero]:[]);return `
 <div class="editor-title"><div><span class="section-label">TOUR PRODUCT</span><h2>${safe(c.title)}</h2><p>기본 정보, 이미지, 노출 설정을 편집합니다.</p></div><span class="status ${c.published===false?"off":"on"}">${c.published===false?"비공개":"공개"}</span></div>
 <div class="edit-block"><div class="block-head"><strong>기본 정보</strong><span>홈페이지 상품 카드와 상세화면에 사용됩니다.</span></div><div class="fields">${field("title","상품명",c.title)}${field("location","지역",c.location)}${field("category","카테고리",c.category)}${field("views","조회수",c.views||0,"number")}${area("description","상품 설명",c.description)}</div></div>
 <div class="edit-block"><div class="block-head"><strong>상품 이미지</strong><span><b>대표 이미지를 직접 체크</b>하고, 이미지는 마우스로 끌어서 순서를 변경할 수 있습니다.</span></div>
 <label class="upload-box" for="imageFiles"><span class="upload-icon">＋</span><strong>이미지 추가</strong><small>JPG, PNG, WEBP · 복수 선택 가능</small><input id="imageFiles" type="file" accept="image/*" multiple onchange="handleImages(this.files)"></label>
 <div class="image-grid">${imgs.map((src,i)=>imageTile(src,i)).join("")||"<div class='image-empty'>등록된 이미지가 없습니다.</div>"}</div></div>
 <div class="edit-block"><div class="block-head"><strong>노출 설정</strong><span>추천 여부와 홈페이지 공개 상태를 정합니다.</span></div><div class="settings-row"><label class="toggle-card"><input id="featured" type="checkbox" ${c.featured?"checked":""}><span><strong>추천상품</strong><small>홈페이지 추천 영역에 노출</small></span></label><label class="toggle-card"><input id="published" type="checkbox" ${c.published===false?"":"checked"}><span><strong>홈페이지 공개</strong><small>고객이 상품을 볼 수 있음</small></span></label><div class="compact-field"><label for="sortOrder">노출순서</label><input id="sortOrder" type="number" value="${c.sortOrder||0}"></div></div></div>
 <div class="editor-actions"><button class="btn primary" onclick="saveCourse()">변경사항 저장</button><button class="btn" onclick="previewCourse()">홈페이지에서 보기</button><button class="btn danger ghost" onclick="removeCourse()">상품 삭제</button></div>
 <div class="child-section"><div class="section-head"><div><span class="section-label">CHILD COURSES</span><h2>하위 여행유형</h2><p><strong>이순신 승전길</strong>처럼 여러 여행방식과 세부코스를 가진 상품을 구성합니다.</p></div><button class="btn secondary" onclick="openGroupForm()">＋ 여행유형 추가</button></div>
 ${(c.groups||[]).map((g,i)=>groupCard(g,i)).join("")||"<div class='empty-admin small'>하위 여행유형이 없습니다.</div>"}</div>`}
function imageTile(src,i){const c=current(),isHero=(c.hero||"")===src;return `<div class="image-tile ${isHero?"is-hero":""}" draggable="true" ondragstart="imageDragStart(${i})" ondragover="imageDragOver(event)" ondrop="imageDrop(event,${i})" ondragend="imageDragEnd()"><div class="drag-hint">⋮⋮ 드래그하여 순서 변경</div><img src="${safe(src)}" alt="상품 이미지 ${i+1}"><div class="image-meta"><label class="hero-check"><input type="radio" name="heroImage" ${isHero?"checked":""} onchange="setHeroImage(${i})"><span>대표 이미지</span></label><div><span class="image-number">#${i+1}</span><button class="mini danger-text" onclick="removeImage(${i})">삭제</button></div></div></div>`}
function groupCard(g,i){return `<div class="group"><div class="group-title"><div><span class="group-label">여행유형 ${i+1}</span><strong>${safe(g.title)}</strong><p>${safe(g.description||"설명 없음")}</p></div><div class="row"><button class="mini" onclick="moveGroup(${i},-1)">↑</button><button class="mini" onclick="moveGroup(${i},1)">↓</button><button class="btn" onclick="openGroupForm('${g.id}')">수정</button><button class="btn secondary" onclick="openRouteForm('${g.id}')">＋ 세부코스</button><button class="btn danger ghost" onclick="removeGroup('${g.id}')">삭제</button></div></div><div class="route-list-admin">${(g.routes||[]).map((r,ri)=>routeRow(g,r,ri)).join("")||"<div class='empty-admin small'>세부코스가 없습니다.</div>"}</div></div>`}
function routeRow(g,r,i){const pointCount=(r.points||[]).length||(r.stops||[]).length;return `<div class="route"><div><strong>${safe(r.title)}</strong><span>${safe(r.area||"-")} · ${r.distance||0}km · 약 ${r.walkHours||0}시간 · 코스지점 ${pointCount}개 · 이미지 ${(r.images||[]).length}장</span></div><div class="row"><button class="mini" onclick="moveRoute('${g.id}',${i},-1)">↑</button><button class="mini" onclick="moveRoute('${g.id}',${i},1)">↓</button><button class="btn" onclick="openRouteForm('${g.id}','${r.id}')">수정</button><button class="btn danger ghost" onclick="removeRoute('${g.id}','${r.id}')">삭제</button></div></div>`}
async function handleImages(files){if(!files?.length)return;const c=current();c.images=c.images?.length?c.images:(c.hero?[c.hero]:[]);for(const file of [...files]){if(!file.type.startsWith("image/"))continue;if(file.size>2*1024*1024){alert(file.name+"은 2MB를 초과해 현재 프로토타입 저장소에 넣을 수 없습니다.");continue}c.images.push(await fileToDataUrl(file))}if(!c.hero)c.hero=c.images[0]||"";persist();render();toast(files.length+"개 이미지 선택을 처리했습니다.")}
function fileToDataUrl(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)})}
function setHeroImage(i){const c=current();c.images=c.images?.length?c.images:(c.hero?[c.hero]:[]);c.hero=c.images[i]||"";persist();render();toast("대표 이미지를 변경했습니다.")}
function imageDragStart(i){dragImageIndex=i;requestAnimationFrame(()=>document.querySelectorAll(".image-tile")[i]?.classList.add("dragging"))}
function imageDragOver(e){e.preventDefault();e.currentTarget.classList.add("drag-over")}
function imageDrop(e,target){e.preventDefault();document.querySelectorAll(".image-tile").forEach(el=>el.classList.remove("drag-over"));if(dragImageIndex===null||dragImageIndex===target)return;const c=current();c.images=c.images?.length?c.images:(c.hero?[c.hero]:[]);const [moved]=c.images.splice(dragImageIndex,1);c.images.splice(target,0,moved);persist();dragImageIndex=null;render();toast("이미지 순서를 변경했습니다.")}
function imageDragEnd(){dragImageIndex=null;document.querySelectorAll(".image-tile").forEach(el=>el.classList.remove("dragging","drag-over"))}
function removeImage(i){const c=current();c.images=c.images?.length?c.images:(c.hero?[c.hero]:[]);const removed=c.images[i];c.images.splice(i,1);if(c.hero===removed)c.hero=c.images[0]||"";persist();render()}
function modal(title,body,saveAction){document.getElementById("modalRoot").innerHTML=`<div class="modal-backdrop" onclick="if(event.target===this)closeModal()"><div class="modal"><div class="modal-head"><div><span class="section-label">EDITOR</span><h2>${title}</h2></div><button class="close" onclick="closeModal()">×</button></div><div class="modal-body">${body}</div><div class="modal-actions"><button class="btn" onclick="closeModal()">취소</button><button class="btn primary" onclick="${saveAction}">저장</button></div></div></div>`}
function closeModal(){document.getElementById("modalRoot").innerHTML="";modalState=null}
function newCourse(){const c={id:uid("course"),title:"새 관광상품",location:"",category:"",description:"",hero:"",images:[],featured:false,published:false,views:0,sortOrder:courses.length+1,groups:[]};courses.push(c);selectedId=c.id;persist();render()}
function pick(id){selectedId=id;render()}
function saveCourse(){const c=current();Object.assign(c,{title:text("title"),location:text("location"),category:text("category"),description:text("description"),views:num("views"),sortOrder:num("sortOrder"),featured:checked("featured"),published:checked("published")});if(!c.hero&&c.images?.length)c.hero=c.images[0];persist();render();toast("관광상품을 저장했습니다.")}
function removeCourse(){if(!confirm("이 상품과 모든 하위코스를 삭제할까요?"))return;courses=courses.filter(c=>c.id!==selectedId);selectedId=courses[0]?.id||null;persist();render()}
function previewCourse(){window.open("../","_blank")}
function openGroupForm(id=null){const c=current(),g=id?c.groups.find(x=>x.id===id):{title:"",description:"",published:true};modalState={type:"group",id};modal(id?"여행유형 수정":"여행유형 추가",`${field("mGroupTitle","여행유형명",g.title)}${area("mGroupDescription","설명",g.description)}<div class="field full checks"><label><input id="mGroupPublished" type="checkbox" ${g.published===false?"":"checked"}> <strong>홈페이지 공개</strong></label></div>`,"saveGroup()")}
function saveGroup(){const c=current();let g=modalState.id?c.groups.find(x=>x.id===modalState.id):null;if(!text("mGroupTitle"))return alert("여행유형명을 입력해주세요.");if(!g){g={id:uid("group"),routes:[]};(c.groups??=[]).push(g)}Object.assign(g,{title:text("mGroupTitle"),description:text("mGroupDescription"),published:checked("mGroupPublished")});persist();closeModal();render()}
function removeGroup(id){if(!confirm("여행유형과 그 안의 세부코스를 삭제할까요?"))return;current().groups=current().groups.filter(g=>g.id!==id);persist();render()}
function routePointRows(points=[]){return points.map((p,i)=>`<div class="point-row" data-point-row><span class="point-order">${i+1}</span><select class="point-type"><option ${p.type==="출발지"?"selected":""}>출발지</option><option ${p.type==="경유지"?"selected":""}>경유지</option><option ${p.type==="도착지"?"selected":""}>도착지</option></select><input class="point-name" placeholder="장소명" value="${safe(p.name||"")}"><input class="point-address" placeholder="주소 또는 위치 설명" value="${safe(p.address||"")}"><button type="button" class="mini danger-text" onclick="this.closest('[data-point-row]').remove();renumberPoints()">삭제</button></div>`).join("")}
function routeImageRows(images=[]){return images.map((src,i)=>`<div class="route-image-tile"><img src="${safe(src)}" alt="세부코스 이미지 ${i+1}"><button type="button" class="mini danger-text" onclick="removePendingRouteImage(${i})">삭제</button></div>`).join("")}
function openRouteForm(gid,rid=null){const g=current().groups.find(x=>x.id===gid),r=rid?g.routes.find(x=>x.id===rid):{title:"",area:"",distance:0,walkHours:0,transportHours:0,difficulty:"보통",description:"",stops:[],points:[],images:[],published:true};const legacy=(r.stops||[]).map((name,i,a)=>({type:i===0?"출발지":i===a.length-1?"도착지":"경유지",name,address:""}));modalState={type:"route",gid,rid,routeImages:[...(r.images||[])],points:[...(r.points?.length?r.points:legacy)]};modal(rid?"세부코스 수정":"세부코스 추가",`<div class="fields">${field("mRouteTitle","세부코스명",r.title)}${field("mRouteArea","지역",r.area)}${field("mRouteDistance","거리(km)",r.distance,"number")}${field("mRouteWalk","트래킹 시간",r.walkHours,"number")}${field("mRouteTransport","차량 이동시간",r.transportHours,"number")}${field("mRouteDifficulty","난이도",r.difficulty)}${area("mRouteDescription","코스 설명",r.description)}</div><div class="modal-section"><div class="modal-section-head"><div><strong>코스 지점</strong><small>출발지 → 경유지 → 도착지 순서로 등록합니다.</small></div><button type="button" class="btn secondary" onclick="addPointRow()">＋ 지점 추가</button></div><div id="pointRows" class="point-rows">${routePointRows(modalState.points)}</div></div><div class="modal-section"><div class="modal-section-head"><div><strong>세부코스 이미지</strong><small>여러 장을 한 번에 선택할 수 있습니다.</small></div><label class="btn secondary route-upload">＋ 이미지 추가<input id="routeImageFiles" type="file" accept="image/*" multiple onchange="handleRouteImages(this.files)"></label></div><div id="routeImageGrid" class="route-image-grid">${routeImageRows(modalState.routeImages)}</div></div><div class="field full checks"><label><input id="mRoutePublished" type="checkbox" ${r.published===false?"":"checked"}> <strong>홈페이지 공개</strong></label></div>`,"saveRoute()")}
function addPointRow(){const box=document.getElementById("pointRows");box.insertAdjacentHTML("beforeend",routePointRows([{type:box.children.length?"경유지":"출발지",name:"",address:""}]));renumberPoints()}
function renumberPoints(){document.querySelectorAll("[data-point-row] .point-order").forEach((el,i)=>el.textContent=i+1)}
function collectPoints(){return [...document.querySelectorAll("[data-point-row]")].map(row=>({type:row.querySelector(".point-type").value,name:row.querySelector(".point-name").value.trim(),address:row.querySelector(".point-address").value.trim()})).filter(p=>p.name)}
async function handleRouteImages(files){for(const file of [...files]){if(!file.type.startsWith("image/"))continue;if(file.size>2*1024*1024){alert(file.name+"은 2MB를 초과해 현재 프로토타입 저장소에 넣을 수 없습니다.");continue}modalState.routeImages.push(await fileToDataUrl(file))}document.getElementById("routeImageGrid").innerHTML=routeImageRows(modalState.routeImages)}
function removePendingRouteImage(i){modalState.routeImages.splice(i,1);document.getElementById("routeImageGrid").innerHTML=routeImageRows(modalState.routeImages)}
function saveRoute(){const {gid,rid}=modalState,g=current().groups.find(x=>x.id===gid);if(!text("mRouteTitle"))return alert("세부코스명을 입력해주세요.");let r=rid?g.routes.find(x=>x.id===rid):null;if(!r){r={id:uid("route"),views:0};(g.routes??=[]).push(r)}const points=collectPoints();Object.assign(r,{title:text("mRouteTitle"),area:text("mRouteArea"),distance:num("mRouteDistance"),walkHours:num("mRouteWalk"),transportHours:num("mRouteTransport"),difficulty:text("mRouteDifficulty")||"보통",description:text("mRouteDescription"),points,stops:points.map(p=>p.name),images:[...modalState.routeImages],published:checked("mRoutePublished")});persist();closeModal();render();toast("세부코스를 저장했습니다.")}
function removeRoute(gid,rid){if(!confirm("세부코스를 삭제할까요?"))return;const g=current().groups.find(x=>x.id===gid);g.routes=g.routes.filter(r=>r.id!==rid);persist();render()}
function move(arr,i,d,rerender=true){const n=i+d;if(n<0||n>=arr.length)return;[arr[i],arr[n]]=[arr[n],arr[i]];persist();if(rerender)render()}
function moveCourse(i,d){move(courses,i,d)}function moveGroup(i,d){move(current().groups,i,d)}function moveRoute(gid,i,d){move(current().groups.find(g=>g.id===gid).routes,i,d)}
function toast(msg){const el=document.createElement("div");el.className="admin-toast";el.textContent=msg;document.body.appendChild(el);setTimeout(()=>el.remove(),1800)}
function soon(name){alert(name+"는 다음 관리모듈에서 연결합니다.")}
render();