(()=>{
let drivers=[],selectedDriverId=null;
const oldRender=window.render,oldRenderVehicles=window.renderVehicles;
const esc=v=>safe(v||"");
const navButtons=active=>`<button class="${active==='courses'?'on':''}" onclick="showCourses()">관광상품 관리</button><button class="${active==='vehicles'?'on':''}" onclick="showVehicles()">차량 관리</button><button class="${active==='drivers'?'on':''}" onclick="showDrivers()">가이드기사 관리</button><button onclick="soon('예약 관리')">예약 관리</button><button onclick="soon('결제 관리')">결제 관리</button><button onclick="soon('사이트 설정')">사이트 설정</button>`;
function patchNav(active){const nav=document.querySelector('.side nav');if(nav)nav.innerHTML=navButtons(active)}
window.render=function(){if(adminSection==='drivers')return renderDrivers();oldRender();patchNav('courses')};
window.renderVehicles=function(){oldRenderVehicles();patchNav('vehicles')};
window.showDrivers=function(){adminSection='drivers';drivers=TourStore.getDrivers();selectedDriverId=selectedDriverId&&drivers.some(d=>d.id===selectedDriverId)?selectedDriverId:(drivers[0]?.id||null);renderDrivers()};
function currentDriver(){return drivers.find(d=>d.id===selectedDriverId)}
function persistDrivers(){TourStore.saveDrivers(drivers)}
window.driverOptions=function(v){
 const active=drivers.filter(d=>d.active!==false),selectedId=v.driverId||'',legacy=v.driverName||v.guide?.name||'';
 return `<div class="driver-match"><div class="driver-search"><label for="vDriverSearch">기사 검색·선택</label><select id="vDriverSearch"><option value="">매칭 기사 없음</option>${active.map(d=>`<option value="${esc(d.id)}" ${selectedId===d.id||(!selectedId&&legacy===d.name)?'selected':''}>${esc(d.name)} · ${esc(d.phone||'연락처 미등록')}</option>`).join('')}</select></div><button type="button" class="btn secondary" onclick="matchDriver()">기사 매칭</button>${selectedId?`<span class="matched-driver">현재 매칭 <b>${esc(drivers.find(d=>d.id===selectedId)?.name||legacy)}</b></span>`:"<span class='matched-driver empty'>매칭 기사 없음</span>"}</div>`;
};
window.matchDriver=function(){const v=currentRide(),id=document.getElementById('vDriverSearch')?.value||'',d=drivers.find(x=>x.id===id);v.driverId=id;v.driverName=d?.name||'';v.guide=d?{name:d.name,rating:d.rating||0,reviews:d.reviews||0,career:d.career||'',languages:d.languages||''}:null;persistRides();renderVehicles();toast(d?d.name+' 기사와 매칭했습니다.':'기사 매칭을 해제했습니다.')};
function renderDrivers(){
 const d=currentDriver();
 root.innerHTML=`<div class="layout"><aside class="side"><div class="logo">TOURFORU <b>RIDE</b><small>ADMIN</small></div><nav>${navButtons('drivers')}</nav><a class="site" href="../" target="_blank">홈페이지 보기 ↗</a></aside><main class="main"><div class="head"><div><span class="eyebrow">GUIDE DRIVER MANAGEMENT</span><h1>가이드기사 관리</h1><p><strong>기사와 차량을 분리 관리</strong>하고 운행할 차량에 필요한 기사를 매칭합니다.</p></div><button class="btn primary large" onclick="newDriver()">＋ 가이드기사 추가</button></div><div class="workspace"><section class="catalog panel"><div class="panel-head"><div><span class="section-label">DRIVERS</span><h2>가이드기사</h2></div><strong class="count">${drivers.length}명</strong></div><div class="list">${drivers.map(x=>`<article class="item ${x.id===selectedDriverId?'on':''}" onclick="pickDriver('${esc(x.id)}')"><div class="driver-list-row">${x.photo?`<img src="${esc(x.photo)}" alt="">`:`<span class="driver-avatar">${esc((x.name||'?').slice(0,1))}</span>`}<div class="item-copy"><strong>${esc(x.name||'이름 미등록')}</strong><span>${esc(x.phone||'연락처 미등록')} · ${esc(x.area||'활동지역 미설정')}</span></div></div><span class="fleet-state ${x.active===false?'off':'on'}">${x.active===false?'중지':'활동'}</span></article>`).join('')||"<div class='empty-admin'>등록된 가이드기사가 없습니다.</div>"}</div></section><section class="editor panel">${d?driverEditor(d):"<div class='empty-admin'>가이드기사를 추가해주세요.</div>"}</section></div></main></div>`;
}
function driverEditor(d){return `<div class="editor-title"><div><span class="section-label">GUIDE DRIVER</span><h2>${esc(d.name||'새 가이드기사')}</h2><p>고객 화면과 차량 매칭에 사용하는 기사 프로필입니다.</p></div><span class="status ${d.active===false?'off':'on'}">${d.active===false?'활동중지':'활동중'}</span></div><div class="driver-profile-grid"><div class="driver-photo-box">${d.photo?`<img src="${esc(d.photo)}" alt="기사 프로필">`:`<div class="driver-photo-empty">프로필 사진</div>`}<label class="btn secondary">사진 선택<input type="file" accept="image/*" onchange="setDriverPhoto(this.files[0])" hidden></label></div><div class="edit-block driver-fields"><div class="fields">${field('dName','이름',d.name)}${field('dPhone','연락처',d.phone||'')}${field('dArea','활동지역',d.area||'')}${field('dLanguages','가능 언어',d.languages||'한국어')}${field('dCareer','가이드·운전 경력',d.career||'')}${field('dLicense','자격·면허',d.license||'')}${field('dRating','평점',d.rating||0,'number')}${field('dReviews','후기 수',d.reviews||0,'number')}</div>${area('dIntro','기사 소개',d.intro||'')}</div></div><div class="driver-bottom"><label class="toggle-card"><input id="dActive" type="checkbox" ${d.active===false?'':'checked'}><span><strong>활동 가능</strong><small>차량 기사 선택 목록에 표시</small></span></label><div class="editor-actions"><button class="btn primary" onclick="saveDriver()">변경사항 저장</button><button class="btn danger ghost" onclick="removeDriver()">기사 삭제</button></div></div>`}
window.pickDriver=id=>{selectedDriverId=id;renderDrivers()};
window.newDriver=()=>{const d={id:uid('driver'),name:'새 가이드기사',phone:'',area:'경남',languages:'한국어',career:'',license:'',intro:'',photo:'',rating:0,reviews:0,active:true};drivers.push(d);selectedDriverId=d.id;persistDrivers();renderDrivers()};
window.saveDriver=()=>{const d=currentDriver();if(!d)return;Object.assign(d,{name:text('dName'),phone:text('dPhone'),area:text('dArea'),languages:text('dLanguages'),career:text('dCareer'),license:text('dLicense'),rating:num('dRating'),reviews:num('dReviews'),intro:text('dIntro'),active:checked('dActive')});persistDrivers();rides.forEach(v=>{if(v.driverId===d.id){v.driverName=d.name;v.guide={name:d.name,rating:d.rating,reviews:d.reviews,career:d.career,languages:d.languages}}});TourStore.saveRides(rides);renderDrivers();toast('가이드기사 정보를 저장했습니다.')};
window.removeDriver=()=>{const d=currentDriver();if(!d||!confirm('이 가이드기사를 삭제할까요?'))return;rides.forEach(v=>{if(v.driverId===d.id){v.driverId='';v.driverName='';v.guide=null}});TourStore.saveRides(rides);drivers=drivers.filter(x=>x.id!==d.id);selectedDriverId=drivers[0]?.id||null;persistDrivers();renderDrivers()};
window.setDriverPhoto=async file=>{if(!file)return;if(!file.type.startsWith('image/'))return alert('이미지 파일을 선택해주세요.');if(file.size>2*1024*1024)return alert('프로필 사진은 2MB 이하로 등록해주세요.');const d=currentDriver();d.photo=await fileToDataUrl(file);persistDrivers();renderDrivers();toast('프로필 사진을 저장했습니다.')};
TourStore.ready().then(()=>{drivers=TourStore.getDrivers();if(adminSection==='drivers')showDrivers()});
})();